// generated by unplugin-vue-components

import '@vue/runtime-core';

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        DemoCounter: typeof import('./components/DemoCounter.vue')['default'];
        ElAside: typeof import('element-plus/es')['ElAside'];
        ElButton: typeof import('element-plus/es')['ElButton'];
        ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider'];
        ElContainer: typeof import('element-plus/es')['ElContainer'];
        ElHeader: typeof import('element-plus/es')['ElHeader'];
        ElIcon: typeof import('element-plus/es')['ElIcon'];
        ElMain: typeof import('element-plus/es')['ElMain'];
        ElMenu: typeof import('element-plus/es')['ElMenu'];
        ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
        ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup'];
        ElProgress: typeof import('element-plus/es')['ElProgress'];
        ElScrollbar: typeof import('element-plus/es')['ElScrollbar'];
        ElSubMenu: typeof import('element-plus/es')['ElSubMenu'];
        ElSwitch: typeof import('element-plus/es')['ElSwitch'];
        IEpDocument: typeof import('~icons/ep/document')['default'];
        IEpFiles: typeof import('~icons/ep/files')['default'];
        IEpLocation: typeof import('~icons/ep/location')['default'];
        IEpMinus: typeof import('~icons/ep/minus')['default'];
        IEpMore: typeof import('~icons/ep/more')['default'];
        IEpPlus: typeof import('~icons/ep/plus')['default'];
        IEpService: typeof import('~icons/ep/service')['default'];
        IEpSetting: typeof import('~icons/ep/setting')['default'];
        RouterLink: typeof import('vue-router')['RouterLink'];
        RouterView: typeof import('vue-router')['RouterView'];
        TheHeader: typeof import('./components/TheHeader.vue')['default'];
        TheSide: typeof import('./components/TheSide.vue')['default'];
    }
}

export {};
